// Auto-generated question bank for the Connection Toolkit.
// easy -> First Date, medium -> Third Date, hard+veryHard -> Deep Connection.

const QUESTIONS = {
  "first-date": {
    category: "First Date",
    icon: "☕",
    questions: [
    { theme: "Connection", text: "What’s your favorite book/movie of all time and why did it speak to you so much?" },
    { theme: "Lifestyle", text: "What’s an ideal weekend for you?" },
    { theme: "Connection", text: "Do you judge a book by its cover?" },
    { theme: "Connection", text: "What is your idea of a perfect vacation?" },
    { theme: "Connection", text: "What are your thoughts on online dating or tinder?" },
    { theme: "Connection", text: "What’s on your bucket list this year?" },
    { theme: "Connection", text: "If a genie granted you 3 wishes right now, what would you wish for?" },
    { theme: "Connection", text: "Where is your favorite place in the entire world to go?" },
    { theme: "Connection", text: "What are your top five favorite movies?" },
    { theme: "Connection", text: "What are some of your favorite songs?" },
    { theme: "Lifestyle", text: "What’s your favorite hobby to do alone?" },
    { theme: "Connection", text: "What’s your biggest pet peeve?" },
    { theme: "Connection", text: "What’s your favorite beer?" },
    { theme: "Connection", text: "Who was your favorite teacher and why?" },
    { theme: "Love", text: "What sport did you fall in love with?" },
    { theme: "Connection", text: "Who is your favorite historical figure?" },
    { theme: "Connection", text: "What made you choose the college you went to?" },
    { theme: "Connection", text: "What food could you not live without?" },
    { theme: "Connection", text: "Dogs or Cats?" },
    { theme: "Connection", text: "What was your best birthday?" },
    { theme: "Connection", text: "What was the last book you read?" },
    { theme: "Connection", text: "Where do you usually get your news?" },
    { theme: "Connection", text: "What song makes you unconditionally happy?" },
    { theme: "Connection", text: "What song makes you unconditionally sad?" },
    { theme: "Connection", text: "What is your favorite song and why?" },
    { theme: "Connection", text: "Do you have a favorite book?" },
    { theme: "Connection", text: "What scene in a movie has evoked the most feelings out of you?" },
    { theme: "Connection", text: "If your life was a movie or a book what would be the title to it?" },
    { theme: "Fun", text: "Tell me a really, really stupid joke that made you laugh." },
    { theme: "Connection", text: "If you could have any animal in the world as a pet, what would it be and why?" },
    { theme: "Connection", text: "If you were given a choice to turn into a zombie or to die, which would you pick?" },
    { theme: "Connection", text: "How do you feel about reading books and personal development?" },
    { theme: "Connection", text: "Do you like animals?" },
    { theme: "Connection", text: "How would you handle holidays, birthdays, special occasions, and so on, when it comes to your two families?" },
    { theme: "Connection", text: "What television programs and movies have made an impact on your life and in what way?" }
    ]
  },
  "third-date": {
    category: "Third Date",
    icon: "🌟",
    questions: [
    { theme: "Connection", text: "What’s your philosophy in life?" },
    { theme: "Growth", text: "What’s the one thing you would like to change about Yourself?" },
    { theme: "Connection", text: "Do you consider yourself an introvert or an extrovert?" },
    { theme: "Family", text: "Which parent are you closer to and why?" },
    { theme: "Connection", text: "What was the best phase in your life?" },
    { theme: "Connection", text: "What was the worst phase in your life?" },
    { theme: "Growth", text: "Is what you’re doing now what you always wanted to do growing up?" },
    { theme: "Connection", text: "What makes you feel accomplished?" },
    { theme: "Connection", text: "Are you more into looks or brains?" },
    { theme: "Love", text: "How do you feel about sharing your password with your partner?" },
    { theme: "Family", text: "What kind of parent do you think you will be?" },
    { theme: "Connection", text: "Who is that one person you can talk to about just anything?" },
    { theme: "Love", text: "Would you relocate for love?" },
    { theme: "Connection", text: "Did you ever write a journal?" },
    { theme: "Connection", text: "What are you most thankful for?" },
    { theme: "Values", text: "Do you believe in second chances?" },
    { theme: "Connection", text: "What’s the one thing that people always misunderstand about you?" },
    { theme: "Love", text: "What did your past relationship teach you?" },
    { theme: "Connection", text: "When have you felt your biggest adrenaline rush?" },
    { theme: "Connection", text: "What is the craziest thing you’ve ever done and would you do it again?" },
    { theme: "Connection", text: "What do you think about when you’re by yourself?" },
    { theme: "Connection", text: "Does your job make you happy?" },
    { theme: "Connection", text: "What did you want to be when you were younger?" },
    { theme: "Connection", text: "How would you describe your best friend?" },
    { theme: "Connection", text: "What’s something you can’t go a day without doing?" },
    { theme: "Connection", text: "What’s the most spontaneous thing you’ve done lately?" },
    { theme: "Love", text: "What’s the craziest thing you’ve ever done for love?" },
    { theme: "Connection", text: "Why do you think you’re still single?" },
    { theme: "Connection", text: "What accomplishment are you most proud of?" },
    { theme: "Connection", text: "What is one dream you have yet to accomplish?" },
    { theme: "Values", text: "What are three things you value most about a person?" },
    { theme: "Connection", text: "Who are five people you are closest with?" },
    { theme: "Connection", text: "If you could live anywhere in the world where would it be?" },
    { theme: "Connection", text: "What’s the most exciting thing that’s happened this past year?" },
    { theme: "Connection", text: "What’s one thing that bothers you most about the world today?" },
    { theme: "Connection", text: "If you could change one thing about yourself what would it be?" },
    { theme: "Connection", text: "If you could change one thing about the world what would it be?" },
    { theme: "Connection", text: "What is the weirdest thing about you?" },
    { theme: "Love", text: "What was your longest relationship?" },
    { theme: "Connection", text: "What would your best friend say is your best quality?" },
    { theme: "Connection", text: "If you could tell your former self one thing right now what would it be?" },
    { theme: "Connection", text: "What’s closest you’ve ever come to being arrested?" },
    { theme: "Connection", text: "What’s one thing you wish you knew how to do?" },
    { theme: "Connection", text: "Where’s one place you’d like to go that you haven’t been?" },
    { theme: "Connection", text: "What are some of your own personal goals in the next 5 years?" },
    { theme: "Connection", text: "What would you consider your greatest accomplishment so far?" },
    { theme: "Connection", text: "If you could get away with anything that you do?" },
    { theme: "Connection", text: "Who is your greatest hero?" },
    { theme: "Connection", text: "What’s the greatest risk you’ve ever taken?" },
    { theme: "Connection", text: "Why are we here?" },
    { theme: "Values", text: "Do you believe in fate?" },
    { theme: "Connection", text: "How do you think people see you?" },
    { theme: "Connection", text: "If you had the ability to erase something that you did in the past, what would it be?" },
    { theme: "Connection", text: "If you could have anybody else’s life, who’s would you take?" },
    { theme: "Connection", text: "What fictional character do you most relate to?" },
    { theme: "Connection", text: "If you could take us anywhere in the world right now, where would you take us?" },
    { theme: "Connection", text: "If you died tomorrow, what would you wish you had done?" },
    { theme: "Connection", text: "Can you pinpoint the moment in your life where you were the happiest?" },
    { theme: "Connection", text: "If past lives are real, what was yours?" },
    { theme: "Connection", text: "Have you ever seen something you can’t explain?" },
    { theme: "Connection", text: "What is your biggest accomplishment?" },
    { theme: "Connection", text: "If you could do one thing without suffering the consequences, what would you do?" },
    { theme: "Connection", text: "What is the strangest dream you’ve ever had?" },
    { theme: "Connection", text: "Is there an activity that calms you?" },
    { theme: "Connection", text: "What makes you feel uneasy?" },
    { theme: "Connection", text: "Can you remember a time in your life you felt the most alive?" },
    { theme: "Connection", text: "Tell me about the facts or harsh truths you choose to ignore but know you shouldn’t." },
    { theme: "Connection", text: "When have you felt like you were living life to the fullest?" },
    { theme: "Connection", text: "What is the first lie you ever told?" },
    { theme: "Connection", text: "Have you always had the same political beliefs?" },
    { theme: "Connection", text: "Where do you find meaning in your life?" },
    { theme: "Love", text: "Have you ever been in love?" },
    { theme: "Vulnerability", text: "Why did you cry the last time you did so?" },
    { theme: "Connection", text: "What has been the biggest change you ever made that made you the most proud of yourself?" },
    { theme: "Love", text: "Think about the people you love the most in your life, what do you do for them?" },
    { theme: "Connection", text: "Is home for you a place or a feeling?" },
    { theme: "Connection", text: "If you could be anywhere other than where you are right now, where would you be and what would you be looking at?" },
    { theme: "Family", text: "What is your most cherished childhood memory?" },
    { theme: "Connection", text: "Have you ever had dreams about a past life?" },
    { theme: "Connection", text: "Do you have any recurring dreams or nightmares?" },
    { theme: "Values", text: "Do you believe more in fate or that we are the creators of our own destinies because we are governed by free will?" },
    { theme: "Values", text: "Do you believe in extraterrestrial life?" },
    { theme: "Connection", text: "Would you find more comfort believing we’re the most advanced species in the universe, or that we’re not?" },
    { theme: "Connection", text: "What do you think was there before the universe came into creation?" },
    { theme: "Values", text: "Do you believe in other dimensions and parallel universes?" },
    { theme: "Connection", text: "How do you define art?" },
    { theme: "Connection", text: "If you could have the option of eradicating pain from your life would you choose to do so?" },
    { theme: "Connection", text: "Is a life exclusive to pleasure (no suffering) worthwhile?" },
    { theme: "Love", text: "Would you rather be loved or love?" },
    { theme: "Connection", text: "How do you define beauty?" },
    { theme: "Connection", text: "Where does happiness come from?" },
    { theme: "Values", text: "Do you believe yourself to be truly free?" },
    { theme: "Connection", text: "Deja-vu: is there anything to it or merely coincidence?" },
    { theme: "Connection", text: "Pick two out of physical chemistry, lifestyle compatibility, emotional compatibility and intellectual compatibility." },
    { theme: "Connection", text: "Show me a music track or a scene from a film that made you tear up." },
    { theme: "Boundaries", text: "If you were given a chance to explore the oceans, go to outer space or visit 50 different countries, which one you choose and why?" },
    { theme: "Connection", text: "Do you think that men are more rational and women are more emotional?" },
    { theme: "Connection", text: "Out of the positive emotions of compassion, positivity, enthusiasm and initiative, which one is your biggest strength?" },
    { theme: "Connection", text: "If you could be President of your country for an hour, what is the one thing that you would change?" },
    { theme: "Connection", text: "Describe your best first kiss." },
    { theme: "Connection", text: "Has another’s pain ever given you joy?" },
    { theme: "Connection", text: "Tell me your biggest strength outside of your workplace." },
    { theme: "Values", text: "If you had to pick one, what is the most important value you would teach your children?" },
    { theme: "Connection", text: "Are you health conscious?" },
    { theme: "Love", text: "Name the one bad quality you wouldn’t mind in a partner." },
    { theme: "Love", text: "Name the one worst quality you cannot tolerate in a partner." },
    { theme: "Connection", text: "If you got a free check for $5,000 right this second, how would you use it?" },
    { theme: "Connection", text: "Name one really surprising thing that set your heart pumping and gave you an adrenaline rush." },
    { theme: "Connection", text: "Have you ever been unable to sleep?" },
    { theme: "Connection", text: "What is the most romantic and loving thing you have ever done for somebody?" },
    { theme: "Connection", text: "What is the most adventurous thing you have ever done in your life?" },
    { theme: "Connection", text: "What’s your day-to-day mantra?" },
    { theme: "Connection", text: "What quote resonates with you more than any other?" },
    { theme: "Connection", text: "What’s your anti-motto?" },
    { theme: "Connection", text: "What trait do you envy in others?" },
    { theme: "Connection", text: "What skill do you wish you had?" },
    { theme: "Connection", text: "How do you wish to be remembered?" },
    { theme: "Connection", text: "How would your best friend describe you in five words?" },
    { theme: "Connection", text: "How would you summarize your life purpose?" },
    { theme: "Connection", text: "Who are you?" },
    { theme: "Connection", text: "What are five reasons a person would want to spend the rest of their life with you and the three reasons they wouldn’t?" },
    { theme: "Connection", text: "What does compatibility mean to you?" },
    { theme: "Love", text: "What is your most important love language?" },
    { theme: "Connection", text: "How do you view money?" },
    { theme: "Connection", text: "How do you feel about prenuptial agreements?" },
    { theme: "Connection", text: "What are some of your aspirations in life?" },
    { theme: "Connection", text: "When something really bothers you about a person, how do you go about expressing it to them?" },
    { theme: "Connection", text: "Who are the 3 people in your life that have positively and negatively influenced you the most?" },
    { theme: "Connection", text: "Which types of personalities do you get along with the most?" },
    { theme: "Connection", text: "Where would you like to be 10 years from now, financially and emotionally?" },
    { theme: "Love", text: "How important is it for you and your partner to stay physically fit?" },
    { theme: "Values", text: "How much do you value personal time with friends, study, reflecting or to recreate yourself?" },
    { theme: "Connection", text: "What are your financial responsibilities and goals?" },
    { theme: "Love", text: "What does love mean to you?" },
    { theme: "Connection", text: "How do you feel about politics?" },
    { theme: "Connection", text: "How do you feel about capitalism, socialism, or communism?" },
    { theme: "Connection", text: "How often do you keep in contact with your Ex?" },
    { theme: "Connection", text: "How do you feel about attention?" },
    { theme: "Connection", text: "How long have you been working at your current company/job?" },
    { theme: "Connection", text: "What’s your expectation of how you want people to respond to you when you’re sick?" },
    { theme: "Connection", text: "What are 3 things that make you happy and 3 things that make you sad?" },
    { theme: "Connection", text: "What are your hobbies and what are some ways you have fun?" },
    { theme: "Connection", text: "Everyone has some skeletons in the closet — what are yours?" },
    { theme: "Love", text: "How would you keep the love life alive if things started to become too much of a routine?" },
    { theme: "Connection", text: "What are your top 3 good and bad habits?" },
    { theme: "Love", text: "How long can you handle your partner being away? 1 week, 1 month, 3 months?" },
    { theme: "Growth", text: "Describe your personal growth journey over the past ten years, including the high and low points." },
    { theme: "Connection", text: "What are three of the most vivid memories you can recall from birth to age 18?" },
    { theme: "Connection", text: "To what extent do you see the way you both communicate as similar and in what way is it different?" },
    { theme: "Love", text: "Describe what your life was like before you met your current partner." },
    { theme: "Connection", text: "What are the questions about me you’ve always wanted to ask but never have?" },
    { theme: "Connection", text: "If something really bothered you about me, how would you go about expressing it to me?" },
    { theme: "Connection", text: "Who are the people in your life that have influenced you the most and in what way?" },
    { theme: "Connection", text: "Ten years from now, where would you like to be emotionally?" },
    { theme: "Connection", text: "When you are sick, how do you want others to respond to you?" },
    { theme: "Connection", text: "What brings you the greatest satisfaction in life?" },
    { theme: "Connection", text: "What are the “must have” and “must not have” qualities in a person you may want to spend the rest of your life with?" },
    { theme: "Love", text: "How do you know you’re in love with your partner?" },
    { theme: "Connection", text: "How would you describe yourself to someone who’s never met you?" },
    { theme: "Connection", text: "If you inherited a large sum of money and could afford to live anywhere in the world, where would it be?" },
    { theme: "Love", text: "What about your partner makes you proud of them?" }
    ]
  },
  "deep-bond": {
    category: "Deep Connection",
    icon: "❤️",
    questions: [
    { theme: "Love", text: "What is a relationship deal breaker for you?" },
    { theme: "Connection", text: "Would you ever take back someone who cheated?" },
    { theme: "Family", text: "What would you do if your parents didn’t like your partner?" },
    { theme: "Connection", text: "Do you usually stay friends with your exes?" },
    { theme: "Connection", text: "Have you ever lost someone close to you?" },
    { theme: "Connection", text: "If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?" },
    { theme: "Connection", text: "Are you confrontational?" },
    { theme: "Connection", text: "When was the last time you broke someone’s heart?" },
    { theme: "Connection", text: "What’s your biggest regret in life?" },
    { theme: "Love", text: "Why did your last relationship end?" },
    { theme: "Growth", text: "What’s been your biggest mistake so far in life and what did you learn from it?" },
    { theme: "Family", text: "What qualities do you admire about your parents?" },
    { theme: "Vulnerability", text: "What is your greatest fear?" },
    { theme: "Growth", text: "What is the greatest struggle you’ve overcome?" },
    { theme: "Connection", text: "Who are you closer with your mom or your dad?" },
    { theme: "Connection", text: "If I asked you at age 5 what you wanted to be when you grew up, what would you say?" },
    { theme: "Vulnerability", text: "What is your biggest irrational fear?" },
    { theme: "Connection", text: "What is your biggest regret?" },
    { theme: "Connection", text: "What is the darkest thought you’ve ever had?" },
    { theme: "Vulnerability", text: "Is there something out there, a thought, an idea, a current event, or a fear that you find deeply unsettling?" },
    { theme: "Vulnerability", text: "What would you consider to be your deepest fear?" },
    { theme: "Connection", text: "What do you do or where do you go when you need to be alone?" },
    { theme: "Connection", text: "What makes you feel like you need to be alone?" },
    { theme: "Connection", text: "When have you felt the lowest in your life?" },
    { theme: "Connection", text: "Where have you felt the most failure?" },
    { theme: "Vulnerability", text: "What is the first secret you ever kept from anybody?" },
    { theme: "Connection", text: "Tell me about the times someone broke your heart." },
    { theme: "Vulnerability", text: "Have you ever cried tears of joy?" },
    { theme: "Connection", text: "What did you do when you hurt someone the most?" },
    { theme: "Connection", text: "When have you caused the most harm to yourself?" },
    { theme: "Connection", text: "Have you ever questioned your sanity and why?" },
    { theme: "Connection", text: "What do you think happens after death, if anything?" },
    { theme: "Connection", text: "If you could be given the date of your death would you want to know it?" },
    { theme: "Connection", text: "Presented with the opportunity to be immortal would you take it?" },
    { theme: "Family", text: "What was your father or mother like at home?" },
    { theme: "Connection", text: "If you were given a choice to choose your manner of death, how would you die?" },
    { theme: "Connection", text: "Out of the negative emotions of greed, anger, jealousy and hate, which one would you say affects you the most?" },
    { theme: "Vulnerability", text: "Tell me your biggest supernatural or paranormal fear?" },
    { theme: "Love", text: "Tell me about the time you were so embarrassed in love you wished you could disappear right there and then." },
    { theme: "Love", text: "Tell me about your biggest love regret that made you wish you could turn back time?" },
    { theme: "Connection", text: "How do you handle difficult times in life?" },
    { theme: "Growth", text: "What’s the worst thing you had to overcome?" },
    { theme: "Family", text: "What were your parents work schedules like growing up?" },
    { theme: "Connection", text: "How were you disciplined as a child?" },
    { theme: "Family", text: "Were either one of your parents an entrepreneur growing up?" },
    { theme: "Communication", text: "How well do you handle constructive criticism and advice?" },
    { theme: "Vulnerability", text: "What 3 things do you fear the most in life?" },
    { theme: "Love", text: "If you didn’t agree with a decision your partner made, how would you go about sharing your frustration with them?" },
    { theme: "Love", text: "Do you believe you and your partner should be honest about everything in your relationship, or should some things be kept private?" },
    { theme: "Connection", text: "What was the lowest point of your life and how did you get out of it?" },
    { theme: "Connection", text: "What 3 events create the most stress in your life and how do you handle them?" },
    { theme: "Love", text: "Do you have a better relationship with your Mom or your Dad?" },
    { theme: "Family", text: "What are some qualities you love about your parents that you would want to have in your partner?" },
    { theme: "Communication", text: "How do you feel about the life of an entrepreneur — the competition, the drive, the late nights, the criticism?" },
    { theme: "Connection", text: "How were you disciplined as a child, and would you raise your own kids the same way?" },
    { theme: "Love", text: "In a relationship, what part of giving of yourself do you struggle with?" },
    { theme: "Connection", text: "Could you describe the people in your life who are the easiest to get along with and those who are the most difficult?" },
    { theme: "Growth", text: "What have you learned about yourself through failure, pain, waiting, financial hardship, disappointment, or criticism?" },
    { theme: "Love", text: "What was your last relationship like, and what are three reasons you’re confident the relationship is over and you can move forward?" },
    { theme: "Connection", text: "Can you think of any loss in your life that you’ve never fully grieved over?" },
    { theme: "Family", text: "What are five adjective you would select to describe your relationship with your father?" },
    { theme: "Family", text: "What are five adjectives you would select to describe your relationship with your mother?" },
    { theme: "Connection", text: "Describe how you handle stress and frustration." },
    { theme: "Love", text: "Everyone brings some baggage into a relationship — what baggage are you bringing, and how much of it is there?" },
    { theme: "Communication", text: "How comfortable are you with confrontation or conflict?" },
    { theme: "Family", text: "What is your idea of a “family”, and what would you change about how you were raised?" },
    { theme: "Family", text: "If I could talk with your parents, what would they say I needed to know about you?" },
    { theme: "Love", text: "On a scale of 0 to 10, to what extent do you experience guilt or anguish over your previous relationships?" },
    { theme: "Connection", text: "Of all the emotions we experience in life, what are the easiest ones for you to express and what are the most difficult?" },
    { theme: "Love", text: "Do you feel you need to compromise or sacrifice anything to be a part of this relationship?" },
    { theme: "Connection", text: "If I messed up in a decision, whether in business or just in general, how would you share your frustration about my decision with me?" },
    { theme: "Love", text: "How frequently do you have contact with your former partner, if any, and in what way?" }
    ]
  },
};

export default QUESTIONS;
